name: sonarr
version: '2.0.0.5252'
summary: Smart PVR for newsgroup and bittorrent users
description: |
  Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS
  feeds for new episodes of your favorite shows and will grab, sort and rename
  them. It can also be configured to automatically upgrade the quality of files
  already downloaded when a better quality format becomes available.

  The web interface is accessible by default at http://localhost:8989

  See https://sonarr.tv for more details.
icon: icon.png
grade: stable
confinement: strict

apps:
  nzbdrone:
    command: usr/bin/mono --debug $SNAP/NzbDrone/NzbDrone.exe -data=$SNAP_COMMON
    environment:
      MONO_CFG_DIR: $SNAP/etc
      MONO_CONFIG: $SNAP/etc/mono/config
      MONO_GAC_PREFIX: $SNAP/usr/lib/mono/gac
      MONO_PATH: $SNAP/usr/lib/mono/4.5
    daemon: simple
    plugs:
      - network
      - network-bind
      - removable-media

parts:
  nzbdrone:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      set -e

      URL="http://download.sonarr.tv/v2/master/mono/NzbDrone.master.${SNAPCRAFT_PROJECT_VERSION}.mono.tar.gz"
      curl "$URL" | tar xz
    override-build: |
      cp -a NzbDrone "$SNAPCRAFT_PART_INSTALL"
    prime:
      - NzbDrone

  deps:
    plugin: dump
    source: .
    stage-packages:
      - libcurl3
      - libmono-accessibility4.0-cil
      - libmono-cairo4.0-cil
      - libmono-cecil-private-cil
      - libmono-codecontracts4.0-cil
      - libmono-compilerservices-symbolwriter4.0-cil
      - libmono-corlib4.5-cil
      - libmono-cscompmgd0.0-cil
      - libmono-csharp4.0c-cil
      - libmono-custommarshalers4.0-cil
      - libmono-data-tds4.0-cil
      - libmono-db2-1.0-cil
      - libmono-debugger-soft4.0a-cil
      - libmono-http4.0-cil
      - libmono-i18n-cjk4.0-cil
      - libmono-i18n-mideast4.0-cil
      - libmono-i18n-other4.0-cil
      - libmono-i18n-rare4.0-cil
      - libmono-i18n-west4.0-cil
      - libmono-i18n4.0-all
      - libmono-i18n4.0-cil
      - libmono-ldap4.0-cil
      - libmono-management4.0-cil
      - libmono-messaging-rabbitmq4.0-cil
      - libmono-messaging4.0-cil
      - libmono-microsoft-build-engine4.0-cil
      - libmono-microsoft-build-framework4.0-cil
      - libmono-microsoft-build-tasks-v4.0-4.0-cil
      - libmono-microsoft-build-utilities-v4.0-4.0-cil
      - libmono-microsoft-build4.0-cil
      - libmono-microsoft-csharp4.0-cil
      - libmono-microsoft-visualc10.0-cil
      - libmono-microsoft-web-infrastructure1.0-cil
      - libmono-oracle4.0-cil
      - libmono-parallel4.0-cil
      - libmono-peapi4.0a-cil
      - libmono-posix4.0-cil
      - libmono-rabbitmq4.0-cil
      - libmono-relaxng4.0-cil
      - libmono-security4.0-cil
      - libmono-sharpzip4.84-cil
      - libmono-simd4.0-cil
      - libmono-smdiagnostics0.0-cil
      - libmono-sqlite4.0-cil
      - libmono-system-componentmodel-composition4.0-cil
      - libmono-system-componentmodel-dataannotations4.0-cil
      - libmono-system-configuration-install4.0-cil
      - libmono-system-configuration4.0-cil
      - libmono-system-core4.0-cil
      - libmono-system-data-datasetextensions4.0-cil
      - libmono-system-data-entity4.0-cil
      - libmono-system-data-linq4.0-cil
      - libmono-system-data-services-client4.0-cil
      - libmono-system-data-services4.0-cil
      - libmono-system-data4.0-cil
      - libmono-system-design4.0-cil
      - libmono-system-drawing-design4.0-cil
      - libmono-system-drawing4.0-cil
      - libmono-system-dynamic4.0-cil
      - libmono-system-enterpriseservices4.0-cil
      - libmono-system-identitymodel-selectors4.0-cil
      - libmono-system-identitymodel4.0-cil
      - libmono-system-io-compression-filesystem4.0-cil
      - libmono-system-io-compression4.0-cil
      - libmono-system-json-microsoft4.0-cil
      - libmono-system-json4.0-cil
      - libmono-system-ldap-protocols4.0-cil
      - libmono-system-ldap4.0-cil
      - libmono-system-management4.0-cil
      - libmono-system-messaging4.0-cil
      - libmono-system-net-http-formatting4.0-cil
      - libmono-system-net-http-webrequest4.0-cil
      - libmono-system-net-http4.0-cil
      - libmono-system-net4.0-cil
      - libmono-system-numerics4.0-cil
      - libmono-system-reactive-core2.2-cil
      - libmono-system-reactive-debugger2.2-cil
      - libmono-system-reactive-experimental2.2-cil
      - libmono-system-reactive-interfaces2.2-cil
      - libmono-system-reactive-linq2.2-cil
      - libmono-system-reactive-observable-aliases0.0-cil
      - libmono-system-reactive-platformservices2.2-cil
      - libmono-system-reactive-providers2.2-cil
      - libmono-system-reactive-runtime-remoting2.2-cil
      - libmono-system-reactive-windows-forms2.2-cil
      - libmono-system-reactive-windows-threading2.2-cil
      - libmono-system-runtime-caching4.0-cil
      - libmono-system-runtime-durableinstancing4.0-cil
      - libmono-system-runtime-serialization-formatters-soap4.0-cil
      - libmono-system-runtime-serialization4.0-cil
      - libmono-system-runtime4.0-cil
      - libmono-system-security4.0-cil
      - libmono-system-servicemodel-activation4.0-cil
      - libmono-system-servicemodel-discovery4.0-cil
      - libmono-system-servicemodel-internals0.0-cil
      - libmono-system-servicemodel-routing4.0-cil
      - libmono-system-servicemodel-web4.0-cil
      - libmono-system-servicemodel4.0a-cil
      - libmono-system-serviceprocess4.0-cil
      - libmono-system-threading-tasks-dataflow4.0-cil
      - libmono-system-transactions4.0-cil
      - libmono-system-web-abstractions4.0-cil
      - libmono-system-web-applicationservices4.0-cil
      - libmono-system-web-dynamicdata4.0-cil
      - libmono-system-web-extensions-design4.0-cil
      - libmono-system-web-extensions4.0-cil
      - libmono-system-web-http-selfhost4.0-cil
      - libmono-system-web-http-webhost4.0-cil
      - libmono-system-web-http4.0-cil
      - libmono-system-web-mvc3.0-cil
      - libmono-system-web-razor2.0-cil
      - libmono-system-web-routing4.0-cil
      - libmono-system-web-services4.0-cil
      - libmono-system-web-webpages-deployment2.0-cil
      - libmono-system-web-webpages-razor2.0-cil
      - libmono-system-web-webpages2.0-cil
      - libmono-system-web4.0-cil
      - libmono-system-windows-forms-datavisualization4.0a-cil
      - libmono-system-windows-forms4.0-cil
      - libmono-system-windows4.0-cil
      - libmono-system-xaml4.0-cil
      - libmono-system-xml-linq4.0-cil
      - libmono-system-xml-serialization4.0-cil
      - libmono-system-xml4.0-cil
      - libmono-tasklets4.0-cil
      - libmono-webbrowser4.0-cil
      - libmono-webmatrix-data4.0-cil
      - libmono-windowsbase4.0-cil
      - libmono-xbuild-tasks4.0-cil
      - mediainfo
      - mono-runtime
      - sqlite3
    override-build: |
      set -e

      snapcraftctl build
      sed -i "s,/usr/lib/,/snap/sonarr/current/usr/lib/,g" $SNAPCRAFT_PART_INSTALL/etc/mono/config
    filesets:
      bins:
        - usr/bin/mono*
        - usr/bin/sqlite*
      libs:
        - lib
        - usr/lib
      etc:
        - etc/mono
        - -etc/mono/2.0
        - -etc/mono/4.0
    stage:
      - $bins
      - $libs
      - $etc
