name: radarr
summary: Smart Movies PVR for Usenet and BitTorrent users
description: |
  Radarr is a movie collection manager for Usenet and BitTorrent users. 
  It can monitor multiple RSS feeds for new movies and will interface with 
  clients and indexers to grab, sort, and rename them. It can also be configured 
  to automatically upgrade the quality of existing files in the library when a 
  better quality format becomes available.

  The web interface is accessible by default at http://localhost:7878

  See https://radarr.video for more details.
license: GPL-3.0+
icon: icon.svg
grade: stable
confinement: strict
base: core20
adopt-info: radarr

layout:
  /usr/share/.mono:
    bind: $SNAP_COMMON/mono

apps:
  radarr:
    command: bin/run-radarr
    daemon: simple
    plugs:
      - mount-observe
      - network
      - network-bind
      - removable-media

parts:
  radarr:
    plugin: nil
    source: 'https://radarr.servarr.com/v1/update/master/updatefile?os=linux'
    source-type: tar
    override-build: |
      INST_DIR="$SNAPCRAFT_PART_INSTALL/Radarr"
      mkdir -p "$INST_DIR"
      cp -a * "$INST_DIR"

      apt install curl jq

      CHECK_URL="https://radarr.servarr.com/v1/update/master/changes?os=linux"

      snapcraftctl set-version "$(curl -s ${CHECK_URL} | jq -r .[0].version)"
    prime:
      - Radarr

  local:
    plugin: dump
    source: snap/local

  snapcraft-preload:
    plugin: cmake
    source: https://github.com/sergiusens/snapcraft-preload.git
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
    organize:
      usr/local/*: /
    prime:
      - -usr

  deps:
    plugin: dump
    source: .
    stage-packages:
      - ca-certificates-mono
      - libcurl4
      - mono-complete
      - mediainfo
      - sqlite3
    filesets:
      bins:
        - usr/bin/mcs
        - usr/bin/mono*
        - usr/bin/sqlite*
      libs:
        - usr/lib
      etc:
        - etc/mono
        - -etc/mono/2.0
        - -etc/mono/4.0
    stage:
      - $bins
      - $libs
      - $etc
